(function(g){var window=this;var Z4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.B,displayName:g.GH(a),kind:a.A,name:a.C,id:a.Ea,is_servable:a.K,is_default:a.isDefault,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},$4=function(a){return a.g?a.g.languageCode:a.l},qza=function(a,b){var c=new g.FH;
c.l=a.l;c.B=a.B;c.C=a.C;c.A=a.A;c.isDefault=!1;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},a5=function(a){if(!rza.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(sza,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},b5=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.pQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.l=k},c5=function(a,b,c,d,e){g.pQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},e5=function(a){a=void 0===a?{}:a;
var b="_"+d5++;return new c5(0,0x8000000000000,0,b,a)},f5=function(a,b,c,d,e,f){var k={};
g.Fa(k,b);g.Fa(k,a.params);g.Fa(k,c);var l={};g.Fa(l,b.fb);a.params.fb&&g.Fa(l,a.params.fb);g.Fa(l,c.fb);k.fb=l;g.W.call(this,{G:"div",L:"caption-window",P:{id:"caption-window-"+a.id,dir:1==k.Ck?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},N:[{G:"span",L:"captions-text"}]});this.B=[];this.K=!1;this.F=a;this.D=[];this.H=[];this.Ca=e;this.xa=f;this.C=null;this.Z=.96*e;this.ia=.96*f;this.o=k;this.sa=c;this.A=this.g["captions-text"];this.na=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.M=d/360*16;this.type=0;this.ea=this.M*tza(l);a=new g.IF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.tO,this);a.subscribe("dragmove",this.sO,this);a.subscribe("dragend",this.rO,this);this.ga=this.fa=0;a="";this.o.Mk&&(a=a5(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.Mk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":uza[this.o.textAlign]};this.na&&(b["border-radius"]=a?this.ea/
8+"px":"");g.mh(this.element,b);switch(this.o.If){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},tza=function(a){var b=1+.25*(a.qj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},g5=function(a,b){var c={},d=b.background?b.background:a.o.fb.background;
if(null!=b.df||b.background){var e=null!=b.df?b.df:a.o.fb.df;d=a5(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.na&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ea/8+"px")}if(null!=b.qj||null!=b.offset)c["font-size"]=a.M*tza(b)+"px";d=1;e=b.color||a.o.fb.color;if(b.color||null!=b.Ih)e=a5(e),d=null==b.Ih?a.o.fb.Ih:b.Ih,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Wh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.Nx&&(k=e=b.Nx);var l=a.M/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.uE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.fb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.qf&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Ds&&(c.visibility="hidden");return c},vza=function(a,b,c){a.K=a.K||!!c;
var d={};g.Fa(d,a.o.fb);g.Fa(d,c||b.l);g.Fa(d,a.sa.fb);c=a.D[0];if(c&&d.background==c.background&&d.df==c.df&&!!d.Ds==!!c.Ds&&d.Wh==c.Wh){var e;for(e=0;e<a.D.length;e++)if(g.Yb(d,a.D[e])){var f=a.H[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Bd("SPAN");g.mh(f,g5(a,e));a.H[0].appendChild(f);e=1}a.H.length=e;a.D.length=e}else a.H.length=0,a.D.length=0,f=g.Bd("SPAN"),g.mh(f,g5(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Hd(a.C),f.appendChild(a.C));c=(k=g.w(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.B){if(0<e||0!=a.B.length){var m=g.Bd("BR");f.appendChild(m)}f.appendChild(g.Cd("\u00a0"));a.C=g.Cd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Cd(l):l,m))}a.D.push(d);a.H.push(f);a.B.push(b)},wza=function(){},i5=function(){this.A=this.l=this.mode=this.o=0;
this.B=new h5(this);this.C=new h5(this);this.g=[];this.clear()},yza=function(a,b,c){if(255==a&&255==b||!a&&!b)return{sn:a,
tn:b,result:0};a=xza[a];b=xza[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{sn:a,tn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{sn:a,tn:b,result:2};return{sn:a,tn:b,result:3}},Aza=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,zza(a.B,b,c,d))},Bza=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?Aza(a,d.Ix,d.Jx,b):1==d.type&&a.o&496&&zza(a.C,d.Ix,d.Jx,b)}a.g.length=0},j5=function(){this.g=0},k5=function(){this.l=this.o=this.g=0},l5=function(){this.timestamp=this.ue=0},m5=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new l5}this.g=this.l=this.row=0;this.style=new j5;this.B=a;this.A=0},n5=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.ue){0==c&&(c=m,d=q);n=String.fromCharCode(r.ue);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.ue||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.ue,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=q.timestamp,v<=e&&(e=v),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Gza=function(a,b){switch(a){case 0:return Cza[(b&127)-32];
case 1:return Dza[b&15];case 2:return Eza[b&31];case 3:return Fza[b&31]}return 0},o5=function(a){return a.o[a.row][a.l]},p5=function(a,b,c){2<=b&&1<a.l&&(--a.l,o5(a).ue=0);
var d=o5(a);d.timestamp=a.B.l+0;d.ue=Gza(b,c);32>a.l&&a.l++},Hza=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].In(a.o[c+e][f])},q5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},r5=function(a){a.row=0<a.g?a.g:1;
a.l=1;q5(a,0,15)},s5=function(a){this.A=a;
this.B=0;this.style=new j5;this.C=new m5(a);this.D=new m5(a);this.F=new m5(a);this.l=this.C;this.o=this.D;this.g=this.l},t5=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:n5(d,c),r5(a.l),r5(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(n5(d,c),q5(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},Iza=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},Jza=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},h5=function(a){this.l=a;
this.g=new k5;this.B=0;this.o=new s5(a);this.C=new s5(a);this.A=this.o},zza=function(a,b,c,d){a.g.update();
b=yza(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.sn;c=b.tn;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&p5(a,0,b),c&96&&p5(a,0,c),0!=b&&0!=c&&3==a.style.g&&n5(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;Hza(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));q5(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:p5(b.g,0,32);break a;case 48:57==c?(b=b.g,o5(b).ue=0,32>b.l&&b.l++):p5(b.g,1,c&15)}break;case 2:c&32&&p5(b.g,2,c&31);break;case 3:c&32&&p5(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Iza(b);break;
case 33:b=b.g;1<b.l&&(--b.l,o5(b).ue=0);break;case 36:b=b.g;d=o5(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:t5(b,2,d);break;case 38:t5(b,3,d);break;case 39:t5(b,4,d);break;case 40:p5(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);r5(d);Jza(b);break;case 43:Jza(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:n5(a,d)}q5(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;n5(a,d);Hza(a,b,b+1,a.g-1);q5(a,a.row,1)}break;case 46:q5(b.o,0,15);break;case 47:n5(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;Iza(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},u5=function(){},v5=function(a){this.l=a;
this.g=null},Lza=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Tr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Kza(d,e,k,b,f,a.firstChild,{},c)},Kza=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.qf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");w5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new b5(a,b,c,d,n.nodeValue,e||0<m,g.Ub(k)?void 0:k));else{var q={};g.Fa(q,k);Kza(a,b,c,d,e||0<m,n,q,l)}}},x5=function(){this.l={};
this.g=null},y5=function(a){this.A={};
this.H={};this.I={};this.B="_"+d5++;this.C=a;this.F={};this.l=this.g=null;this.D=!0},z5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},A5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},B5=function(a,b){var c=z5(a,b);
if(void 0!=c)return c},C5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return w5.test(c),c},Mza=function(a,b){var c={},d=b.getAttribute("ws");
g.Fa(c,d?a.I[d]:a.C);d=B5(b,"mh");null!=d&&(c.Lt=d);d=B5(b,"ju");null!=d&&(c.textAlign=d);d=B5(b,"pd");null!=d&&(c.Ck=d);d=C5(b,"wfc");null!=d&&(c.windowColor=d);d=z5(b,"wfo");void 0!=d&&(c.Mk=d/255);return c},Nza=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Fa(c,a.H[d]);d=B5(b,"ap");null!=d&&(c.If=d);d=z5(b,"cc");null!=d&&(c.zr=d);d=z5(b,"ah");null!=d&&(c.Pe=d);d=z5(b,"rc");null!=d&&(c.Mp=d);d=z5(b,"av");null!=d&&(c.kg=d);return c},Oza=function(a,b,c,d){var e={};
g.Fa(e,Nza(a,b));g.Fa(e,Mza(a,b));d?g.Yb(e,a.C)?(d=a.B,e=a.C):d="_"+d5++:d=b.getAttribute("id")||"_"+d5++;a=z5(b,"t")+c;b=z5(b,"d")||0x8000000000000;return new c5(a,b,0,d,e)},D5=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},E5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},F5=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},G5=function(a,b){this.l=a;
this.track="CC3"==b.B?4:0;this.g=new i5;this.g.o=1<<this.track},Qza=function(a){if(g.w(a))return!1;
a=new D5(a,8,0);return Pza(a)},Pza=function(a){if(!(a.g<a.l.byteLength)||1380139777!=F5(a))return!1;
a.version=E5(a);if(1<a.version)return!1;E5(a);E5(a);E5(a);return!0},Rza=function(){this.l=[];
this.g=[]},H5=function(a,b){return b?a.g.concat(a.l):a.g},I5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ja(c,(0,g.A)(b.I,b))||c.push(b);break;default:c=a.g,g.Ja(c,(0,g.A)(b.I,b))||c.push(b)}},J5=function(){},Sza=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.qf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new b5(b,c,d,e.id,q.nodeValue,f||0<n,g.Ub(l)?void 0:l),m.push(q),e.l.push(q);else{var r={};g.Fa(r,l);Sza(a,b,c,d,e,!0,q,r,m)}}},K5=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},Tza=function(a,b,c,d){d=Object.assign({Lt:0},d);
return new c5(a,b,c,"_"+d5++,d)},L5=function(a){g.M.call(this);
this.Vz=!!a;this.l=new Rza;this.D=[];this.g=null},Vza=function(a){var b={};
if(a=$4(a))b.lang=a,Uza.test(a)&&(b.Ck=1);return b},Wza=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.w(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.sJ(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),Qza(b)||(b=g.be(new window.Uint8Array(b))))}if(g.w(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new J5),a.g.o(b,d);b=g.Tr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new y5(Vza(c)):a.g=new x5:a.g=new v5(Vza(c)));return a.g.o(b,d)}try{if(Qza(b))return a.g||(a.g=
new G5(e,c)),a.g.o(b,d)}catch(k){g.QD(k)}return[]},M5=function(a){L5.call(this,a.zn);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},N5=function(){this.kb=[]},O5=function(a,b,c,d,e,f){g.M.call(this);
this.J=a;this.A=b;this.C=new N5;this.g=null;this.H=d;this.K=f;this.o=this.l=null;this.F=c;this.D=e||!1;this.I=new g.Wt(this.pA,1E3,this);g.N(this,this.I);this.B=new g.DF(this);g.N(this,this.B);this.B.O(b,"seekto",this.rB);this.rB(b.getCurrentTime());this.pA()},Xza=function(a,b){var c=a.g;
a.g=g.Ha(a.F.yg(b).g);c!=a.g&&a.K&&a.K()},Yza=function(a,b){var c=g.PK(b,a.J,{}).Sa(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.o=g.JE(c,d,3,100).then((0,g.A)(a.fT,a));a.l=b;c=a.C;d=a.l.g[0].wa;var e=g.bb(c.kb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.kb[e-1]&&e<c.kb.length&&1==c.kb[e]-d?(g.Ra(c.kb,e),g.Ra(c.kb,e-1)):0<e&&1==d-c.kb[e-1]?c.kb[e-1]=d:e<c.kb.length&&1==c.kb[e]-d?c.kb[e]=d:(g.Ya(c.kb,e,0,d),g.Ya(c.kb,e+1,0,d)))},P5=function(a,b){L5.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},Zza=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.rL(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.XH(d.info.mimeType)&&("386"!=c||g.Y(a.A).experiments.g("html5_manifestless_captions_fmt3")))return d}return null},Q5=function(a,b){return a.ya&&null!=a.oa||g.Y(b).Pa&&null!=a.oa&&null!=a.oa.g.rawcc},R5=function(a,b,c,d,e,f){f5.call(this,a,b,c,d,e,f);
this.type=1},S5=function(a,b,c,d,e,f){f5.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.J=this.R=0;this.X=this.I=window.NaN;this.ra=null;this.ba=new g.Wt(this.jT,433,this);g.N(this,this.ba)},T5=function(a){if(!a.R){var b=g.Bd("SPAN");
g.mh(b,g5(a,a.o.fb));a.A.appendChild(b);b.appendChild(g.Cd("M"));var c=b.offsetHeight,d=g.Bd("BR");b.appendChild(d);b.appendChild(g.Cd("M"));a.R=b.offsetHeight-c;a.A.removeChild(b)}return a.R},$za=function(a){if((0,window.isNaN)(a.I)){var b=a.o.zr;
if(b){var c=g.Bd("SPAN");g.Pd(c,"\u2013".repeat(b));g.mh(c,g5(a,a.o.fb));a.A.appendChild(c);a.I=c.offsetWidth;a.A.removeChild(c)}else a.I=0}return a.I},U5=function(a,b,c,d){L5.call(this,d);
c=c||g.bE(a).hl||"";c=c.split("_").join("-");this.B=g.dE(a,{hl:c});this.A=b;this.C={};this.o=null},X5=function(a){g.zV.call(this,a);
this.A=g.Y(a);this.o=a.getVideoData();this.na=g.cV(a);this.I=a;var b=null,c=g.mD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.WC(c));this.Z=b;this.C={fb:{}};this.F={fb:{}};this.M=[];this.R={};this.Y={};this.K=!1;this.ra="1"==this.o.jc.cc_auto_caps||"1"==this.A.Vb.cc_auto_caps;b="3"==this.A.A&&!!a.app.B&&a.app.B.Bm();this.D=(c=!this.A.experiments.g("web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.o.ya:b;this.ga=c&&b&&this.o.ya&&Q5(this.o,this.I);c=b=this.l=this.B=
this.H=this.J=this.X=this.ia=null;this.D||(b=new g.Tt(this.QE,void 0,this),g.N(this,b),c=new g.Wt(this.UU,2E3,this),g.N(this,c));this.ba=b;this.fa=c;this.W=new g.DF(this);g.N(this,this.W);this.D||this.W.O(a,"resize",this.Hv);this.W.O(a,"onPlaybackAudioChange",this.iQ);this.W.O(a,"crn_captions",this.wM,this);this.W.O(a,"crx_captions",this.xM,this);V5(this,W5(this,"display-settings")||{})},aAa=function(a){if(1==a.A.Yg||1==a.o.Yg||"alwayson"==g.MO(a.o,"yt:cc"))return!0;
if(2==a.A.Yg){var b=W5(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.g.getAudioTrack().sr;return"ON"==c||"on"==g.MO(a.o,"yt:cc")},Y5=function(a,b){if(a.l&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.g.getAudioTrack();return!!c.Yn||"FORCED_ON"==c.sr},$5=function(a,b){if(a.B){var c=H5(a.B.l,b||a.ra);
if(a.H&&a.H.g)return a.H.g;for(var d=[a.o.Xg,a.A.Xg,g.MO(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if($4(c[f])==d[e])return c[f];return a.H&&a.H.Kr?a.H.Kr:(d=c.find(function(a){return a.isDefault}))?d:c[0]||Z5(a)}return null},Z5=function(a){return a.H&&a.H.Yn},bAa=function(a,b){for(var c=a.I.app.B.la().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},b6=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&a6(a,"module-enabled",!!b));a.l=b;Y5(a)&&(a.l=Z5(a));a.load(d)},cAa=function(a){if(a.l!=Z5(a)){if(a.K&&!g.OM(a.A)&&!g.VM(a.A)){g.Zt(a.fa);
var b=e5({If:0,Pe:5,kg:5,Mp:2,textAlign:0,Ck:0,lang:"es"});a.X=[b];var c=["Haz clic en "," para ir a la configuraci\u00f3n"];if(!a.ia){var d=new g.jH(g.hpa());g.N(a,d);a.ia=d.element}d=b.end-b.start;var e=g.GH(a.l);e&&a.X.push(new b5(b.start,d,0,b.id,e));a.X.push(new b5(b.start,d,0,b.id,c[0]),new b5(b.start,d,0,b.id,a.ia,!0),new b5(b.start,d,0,b.id,c[1],!0));g.oV(a.g,a.X);g.Xt(a.fa)}if(a.K||g.OM(a.A))a6(a,"module-enabled",!0),a.H&&(a.H.g=a.l);(a=g.aV(a.g.app))&&a.C&&g.eP(a.C.o)}},dAa=function(a,b){var c=
g.$_(a.na,!0).height;
if(!c)return null;var d=a.na.Na();switch(null!=b.params.Lt?b.params.Lt:b.params.FV?2:1<b.l.length?1:0){case 1:return new R5(b,a.C,a.F,c,d.width,d.height);case 2:return new S5(b,a.C,a.F,c,d.width,d.height);default:return new f5(b,a.C,a.F,c,d.width,d.height)}},V5=function(a,b,c){var d=c6.fb;
a.C={};g.Fa(a.C,c6);a.C.fb={};g.Fa(a.C.fb,d);a.F={fb:{}};var e=b.backgroundOverride?a.F:a.C,f=b.background||d.background;w5.test(f);e.fb.background=f;e=b.colorOverride?a.F:a.C;f=b.color||d.color;w5.test(f);e.fb.color=f;e=b.windowColorOverride?a.F:a.C;f=b.windowColor||c6.windowColor;w5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.C;f=b.backgroundOpacity;null==f&&(f=d.df);e.fb.df=f;e=b.fontSizeIncrementOverride?a.F:a.C;f=b.fontSizeIncrement;null==f&&(f=d.qj);e.fb.qj=f;f=b.fontStyleOverride?
a.F:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.qf?3:d.bold?1:d.qf?2:0);f=f.fb;switch(e){case 1:f.bold=!0;delete f.qf;break;case 2:delete f.bold;f.qf=!0;break;case 3:f.bold=!0;f.qf=!0;break;default:delete f.bold,delete f.qf}e=b.textOpacityOverride?a.F:a.C;f=b.textOpacity;null==f&&(f=d.Ih);e.fb.Ih=f;e=b.windowOpacityOverride?a.F:a.C;f=b.windowOpacity;null==f&&(f=c6.Mk);e.Mk=f;e=b.charEdgeStyleOverride?a.F:a.C;f=b.charEdgeStyle;null==f&&(f=d.Wh);e.fb.Wh=f;e=b.fontFamilyOverride?a.F:a.C;f=b.fontFamily;null==
f&&(f=d.fontFamily);e.fb.fontFamily=f;a.loaded&&a.Hv();c&&a6(a,"display-settings",b)},fAa=function(a,b){if(b&&!a.J){var c=e5({Ck:0,
lang:"es"});a.J=[c,new b5(c.start,c.end-c.start,0,c.id,"Los subt\u00edtulos tendr\u00e1n este aspecto")];g.oV(a.g,a.J)}else!b&&a.J&&(eAa(a,a.J),a.J=null)},eAa=function(a,b){g.qV(a.g,b);
(0,g.C)(b,function(a){g.Sa(this.M,a)},a);
a.ba.sl()},gAa=function(a,b){return a&&g.w(a)&&w5.test(a)?a:b},hAa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},iAa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.$c(a,-2,4):b},W5=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},a6=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.sY.prototype.jj=g.ca(9,function(){for(var a=g.nd(window.document,"track",void 0,this.g),b=0;b<a.length;b++)g.Hd(a[b])});
g.O_.prototype.jj=g.ca(8,function(){this.g.jj()});
g.sY.prototype.Bm=g.ca(7,function(){return!!this.g.textTracks});
g.O_.prototype.Bm=g.ca(6,function(){return this.g.Bm()});
g.sY.prototype.Ok=g.ca(5,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.O_.prototype.Ok=g.ca(4,function(a){this.g.Ok(a)});
g.ZI.prototype.lo=g.ca(2,function(a){return(a=this.di(a))?a.l:0});
g.gL.prototype.lo=g.ca(1,function(){return 0});
g.FH.prototype.I=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var Uza=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,sza=/#(.)(.)(.)/,rza=/^#(?:[0-9a-f]{3}){1,2}$/i,w5=/^#(?:[0-9a-f]{3}){1,2}$/i;var uza=["left","right","center"];var c6={windowColor:"#080808",Mk:0,textAlign:2,If:7,Pe:50,kg:100,fb:{background:"#080808",df:.75,Wh:0,color:"#fff",fontFamily:4,qj:0,Ih:1,offset:1}};g.t(b5,g.pQ);g.t(c5,g.pQ);var d5=0;g.t(f5,g.W);g.h=f5.prototype;g.h.tO=function(a,b){var c=g.Dh(this.element,this.element.parentElement);this.fa=a-c.x;this.ga=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.sO=function(a,b){var c=g.Gh(this.element),d=a-this.fa-.02*this.Ca,e=b-this.ga-.02*this.xa,f=(d+c.width/2)/this.Z*3;f=Math.floor(g.$c(f,0,2));var k=(e+c.height/2)/this.ia*3;k=Math.floor(g.$c(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Z;d=100*g.$c(d,0,1);c=(e+k/2*c.height)/this.ia;c=100*g.$c(c,0,1);this.F.params.If=l;this.F.params.kg=c;this.F.params.Pe=d;this.o.If=l;this.o.kg=c;this.o.Pe=d;this.HD()};
g.h.rO=function(){g.lq(this.element,"ytp-dragging")};
g.h.HD=function(){this.Pi(this.B)};
g.h.Sb=function(){return this.type};
g.h.Pi=function(a){var b=Math.min(this.Vy(),this.Z),c=this.Uy();g.mh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gr(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.Pe+2,e=this.o.If;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.kg+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.mh(this.element,a)};
g.h.gr=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.K||this.B.length>b)b=0,this.K=!1,this.B=[],this.D=[],this.H=[],this.C=null,g.Fd(this.A);for(;b<a.length;b++)vza(this,a[b])};
g.h.Vy=function(){return 0};
g.h.Uy=function(){return 0};wza.prototype.B=function(){};i5.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
i5.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var xza=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];j5.prototype.set=function(a){this.g=a};
j5.prototype.get=function(){return this.g};
k5.prototype.clear=function(){this.g=0};
k5.prototype.update=function(){this.g=2==this.g?1:0};
k5.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
l5.prototype.In=function(a){this.ue=a.ue;this.timestamp=a.timestamp};
l5.prototype.reset=function(){this.timestamp=this.ue=0};
m5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.ue?a+"_":a+String.fromCharCode(d.ue)}a+="\n"}return a};
m5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var Cza=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Dza=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Eza=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Fza=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];s5.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
h5.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};u5.prototype.reset=function(){};g.t(v5,u5);v5.prototype.o=function(a){var b=[];this.g||(this.g=e5(this.l),b.push(this.g));a=Array.from(a.firstChild.childNodes);a=g.p(a);for(var c=a.next();!c.done;c=a.next())Lza(c.value,this.g.id,b);return b};g.t(x5,u5);
x5.prototype.o=function(a){var b=[];this.g||(this.g=e5(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=e5());
var k={};f&&(g.Fa(k,f.params),f=f.params.fb)&&(k.fb={},g.Fa(k.fb,f));e.getAttribute("rc")&&(k.Mp=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.zr=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.If=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Pe=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.kg=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Ck=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Ck=0));e.getAttribute("bc")&&(k.fb||(k.fb={}),k.fb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.fb||(k.fb={}),k.fb.df=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.fb||(k.fb={}),k.fb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.FV=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+d5++;c=new c5(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],Lza(a,this.g.id,d),d=g.p(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.t(y5,u5);y5.prototype.reset=function(){this.F={};this.l=this.g=null;this.D=!0};
y5.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Fa(l,this.A[m]);m=A5(c,"b");null!=
m&&(l.bold=m);m=A5(c,"i");null!=m&&(l.qf=m);m=A5(c,"u");null!=m&&(l.underline=m);m=B5(c,"et");null!=m&&(l.Wh=m);m=B5(c,"of");null!=m&&(l.offset=m);m=C5(c,"bc");null!=m&&(l.background=m);m=C5(c,"ec");null!=m&&(l.Nx=m);m=C5(c,"fc");null!=m&&(l.color=m);m=B5(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=z5(c,"sz");void 0!=m&&(l.qj=m/100-1);m=z5(c,"bo");void 0!=m&&(l.df=m/255);c=z5(c,"fo");void 0!=c&&(l.Ih=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.I[d]=Mza(this,c);break;case "wp":d=c.getAttribute("id"),
this.H[d]=Nza(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=Oza(this,d,e,!1);(d=this.F[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.F[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!A5(d,"a");n=(z5(d,"t")||0)+n;var q=z5(d,"d")||5E3;m||(!this.D&&this.l&&this.l.windowId==l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=
""));var r=m?6:5,v=this.A[d.getAttribute("p")],D=d.childNodes;D.length&&(this.D=null!=d.getAttribute("d"));for(var H=0;H<D.length;H++){var L=D[H];0<H&&(m=!0);var T=void 0;1==L.nodeType&&(T=L);if(T&&"s"==T.tagName){var ha=T;L=n;T=q;var db=l,sa=m,Td=r,yh=ha.textContent?ha.textContent:"",qb=this.A[ha.getAttribute("p")];ha=z5(ha,"t")||0;L=new b5(L+ha,T-ha,Td,db,yh,sa,qb)}else L=new b5(n,q,r,l,L.textContent||"",m,v);k.push(L);this.l=L}if(0<k.length)for(k[0].windowId==this.B&&(this.g=Oza(this,d,e,!0),c.push(this.g)),
d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,this.g.l.push(k),c.push(k)}e=c}else e=[];return e};g.t(D5,wza);D5.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+d5++;c=c/1E3-this.D;d=d/1E3-this.D;a=new c5(c,d-c,5,f,{textAlign:0,If:0,Pe:2.5*b,kg:5.33*a});e=new b5(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.t(G5,u5);G5.prototype.o=function(a){a=new D5(a,a.byteLength,this.l);if(Pza(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=F5(a)*(1E3/45):1==a.version&&(a.A=4294967296*F5(a)+F5(a)),a.C=E5(a);0<a.C;a.C--){var b=E5(a),c=E5(a),d=E5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,Ix:c,Jx:d,order:b.g.length}))}Bza(this.g,a);return a.o}return[]};
G5.prototype.reset=function(){this.g.clear()};g.t(J5,u5);
J5.prototype.o=function(a,b){for(var c=[],d=a.split(jAa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!kAa.test(f)){var l=d6.exec(f);if(l&&4<=l.length){var m=K5(l[1]),n=K5(l[2])-m;m+=k;var q,r=q=void 0,v=void 0,D=void 0,H=l[3];l={textAlign:2};H=g.p(H?H.split(" "):[]);for(var L=H.next();!L.done;L=H.next())if(L=L.value.split(":"),2==L.length){var T=L[1];switch(L[0]){case "line":L=T.split(",");L[0].endsWith("%")&&(D=L[0],l.kg=Number.parseInt(D,10),2==L.length&&(v=L[1].trim()));break;case "position":L=T.split(",");
r=L[0];l.Pe=Number.parseInt(r,10);2==L.length&&(q=L[1].trim());break;case "align":switch(T){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}D||(l.kg=100,v||(v="end"));if(!r)switch(l.textAlign){case 0:l.Pe=0;break;case 1:l.Pe=100;break;default:l.Pe=50}r=0;switch(v){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(q){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.If=0>r||8<r?7:r;q=l;f=f.substring(d6.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=Tza(m,n,5,r),n=new b5(m,n,5,k.id,q,!1,g.Ub(f)?void 0:f),c.push(k),c.push(n),k.l.push(n);else for(v=q.split(lAa),1==v.length?(q=5,r=Tza(m,n,q,r)):(D=q=6,r=Object.assign({zr:32},r),r=new c5(m,n,D,"_"+d5++,r)),c.push(r),D=m,l=0;l<v.length;l++)H=v[l],0==l%2?(L=g.Tr("<html>"+H+"</html>"),L.getElementsByTagName("parsererror").length?
(T=L.createElement("span"),T.appendChild(L.createTextNode(H))):T=L.firstChild,Sza(this,D,n-(D-m),q,r,0<l,T,f,c)):D=K5(H)+k}d6.lastIndex=0}}return c};
var kAa=/^NOTE/,jAa=/(?:\r\n|\r|\n){2,}/,d6=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),lAa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(L5,g.M);L5.prototype.trackCount=function(){return H5(this.l,!0).length};
L5.prototype.Nd=function(){this.g=null};
L5.prototype.V=function(){g.M.prototype.V.call(this);this.Nd()};
L5.prototype.pD=function(){return!1};g.t(M5,L5);g.h=M5.prototype;g.h.Ft=function(a,b){var c=this.pl(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.Nd();this.o=g.lE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Gt=function(a,b,c,d){this.A=c;if(d)for(b=g.p(d.captionTracks),c=b.next();!c.done;c=b.next())I5(this.l,c.value);a()};
g.h.pl=function(a){var b=a.Sa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.dE(b,c)};
g.h.Nd=function(){L5.prototype.Nd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Nd();L5.prototype.V.call(this)};N5.prototype.contains=function(a){a=g.bb(this.kb,a);return 0<=a||0>a&&1==(-a-1)%2};
N5.prototype.length=function(){return this.kb.length/2};g.t(O5,g.M);g.h=O5.prototype;g.h.V=function(){g.M.prototype.V.call(this);this.o&&this.o.cancel()};
g.h.rB=function(a){var b=this;if(this.F.Sj())var c=this.B.O(this.A,"progresssync",function(){b.F.index.Ib()&&(b.reset(),b.g=null,Xza(b,b.A.getCurrentTime()),b.B.Da(c))});
else Xza(this,a)};
g.h.reset=function(){this.C=new N5;this.o&&(this.o.cancel(),this.o=null)};
g.h.pA=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Fg(a);!a||this.o||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.Yj(a),!g.Y(this.A).experiments.g("disable_captions_unknown_requests")&&!a.g[0].duration)||(this.C.contains(a.g[0].wa)||Yza(this,a),this.g=g.Ha(a.g));this.I.start()};
g.h.fT=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.Y(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.mL(a);if(c){a=g.PK(this.l,this.J,{});b=this.l;g.LK(b.l,a,c);b.requestId=a.get("req_id");Yza(this,this.l);return}}b||null===this.H||(this.D?this.H(a.response,1E3*this.l.g[0].startTime,this.l.g[0].wa):this.H(a.responseText,1E3*this.l.g[0].startTime,this.l.g[0].wa));this.o=this.l=null};g.t(P5,L5);g.h=P5.prototype;g.h.Ft=function(a,b){this.Nd();var c=Zza(this,a.l);if(c){var d=c.index.lo(c.index.hf());g.Y(this.A).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Ld(c.index.hf()));d*=1E3;var e=g.Y(this.A).Pa;this.B=new O5(new g.uK,this.A,c,function(c,e,l){b(c,a,e,d,l)},e||g.TH(c.info),(0,g.A)(function(){this.B&&this.B.reset();
this.g&&this.g.reset();this.C=!0},this))}};
g.h.pD=function(){var a=this.C;this.C=!1;return a};
g.h.Gt=function(a){if(g.Y(this.A).Pa)I5(this.l,new g.FH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),I5(this.l,new g.FH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g){var c=this.o.g[b];if(g.XH(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||g.Y(this.A).experiments.g("html5_manifestless_captions_fmt3"))){var d="en",e="English",f=".en";if(c=c.info.captionTrack)d=
c.languageCode,e=c.displayName,f=c.vssId;I5(this.l,new g.FH({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Nd=function(){L5.prototype.Nd.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.pl=function(){return""};
g.h.V=function(){this.Nd();L5.prototype.V.call(this)};g.t(R5,f5);R5.prototype.gr=function(a){var b=this.F.l;f5.prototype.gr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Fa(d,c.l);g.Fa(d,mAa);var e=c.l;var f=d}vza(this,c,d)}};
var mAa={Ds:!0};g.t(S5,f5);g.h=S5.prototype;g.h.HD=function(){g.Yt(this.ba)};
g.h.jT=function(){g.lq(this.element,"ytp-rollup-mode");this.Pi(this.ra,!0)};
g.h.Vy=function(){return this.J};
g.h.Uy=function(){return this.F.params.Mp*T5(this)};
g.h.Pi=function(a,b){this.ra=a;if(T5(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.J;this.J=0;f5.prototype.Pi.call(this,a);d=this.A.offsetWidth+1;this.J=Math.max($za(this),c,d);c=this.F.params.Mp*T5(this)-this.A.offsetHeight;c!=this.X&&(b||(0,window.isNaN)(this.X)||(g.S(this.element,"ytp-rollup-mode"),g.Xt(this.ba)),g.mh(this.A,"transform",c?"translateY("+c+"px)":""),this.X=c);f5.prototype.Pi.call(this,a)}else f5.prototype.Pi.call(this,
a)};g.t(U5,L5);g.h=U5.prototype;g.h.Ft=function(a,b){var c=this.pl(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.Nd();this.o=g.lE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Gt=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Vz&&(b.asrs=1);d=g.dE(d,b);b=(0,g.A)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.p(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),D=m.getAttribute("id"),H="true"==m.getAttribute("lang_default"),
L="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");I5(d,new g.FH({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:v,id:D,is_servable:!0,is_translateable:L,vss_id:m,is_default:H}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),v="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:r,
is_default:v},this.C[l.languageCode]=l.languageName,this.D.push(new g.EH(l))}a()},this);
this.Nd();this.o=g.lE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.pl=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.C,kind:a.A,fmt:a.o};a.g&&(c.tlang=$4(a));return b=g.dE(b,c)};
g.h.Nd=function(){L5.prototype.Nd.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Nd();L5.prototype.V.call(this)};g.t(X5,g.zV);g.h=X5.prototype;g.h.V=function(){if(this.D){var a=this.I.app.B;a&&a.jj()}else fAa(this,!1);g.zV.prototype.V.call(this)};
g.h.PA=function(){return this.D?!this.o.ya:this.ga||Y5(this)?!0:aAa(this)};
g.h.load=function(a){g.zV.prototype.load.call(this);this.H=this.g.getAudioTrack();if(this.B||a)this.l&&(this.D&&!this.A.experiments.g("disable_native_caption_api")?bAa(this,!0):a?this.ZC(a,this.l):3!=this.g.Ra()&&this.B.Ft(this.l,(0,g.A)(this.ZC,this))),this.l&&this.l!=Z5(this)?this.g.va("captionschanged",Z4(this.l)):this.g.va("onCaptionsTrackListChanged");else{var b;Q5(this.o,this.I)?b=new P5(this.o.oa,this.g):this.o.captionTracks.length?b=new M5(this.o):b=new U5(this.o.An,this.o.videoId,this.o.Xg||
this.A.Xg||g.MO(this.o,"yt:cc_default_lang")||this.A.xa,this.o.zn);this.B=b;b.Gt((0,g.A)(this.OT,this),!0,this.D?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.D?this.A.experiments.g("disable_native_caption_api")?this.I.app.B.jj():this.l&&bAa(this,!1):(this.fa&&g.Zt(this.fa),g.rV(this.g,"captions"),this.M=[],this.B&&this.B.Nd(),this.J&&g.oV(this.g,this.J),this.Hv());g.zV.prototype.unload.call(this);var a=g.aV(this.g.app);a&&a.C&&g.eP(a.C.o);this.g.va("captionschanged",{})};
g.h.OT=function(){var a;this.K||aAa(this)?a=$5(this,this.K):Y5(this)&&(a=Z5(this));if(this.D||this.ga){for(var b=H5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.GH(e),srclang:$4(e),id:e.toString()};this.ga||(f.src=this.B.pl(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}this.I.app.B.Ok(c);(a=this.I.app.B.la())&&a.textTracks&&a.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.W.O(a.textTracks,"change",this.PT)}else!this.l&&a&&
b6(this,a),this.g.va("onCaptionsTrackListChanged"),this.g.va("onApiChange")};
g.h.PT=function(){for(var a=this.I.app.B.la().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=H5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&b6(this,b,!0)};
g.h.RV=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.D&&this.unload():!this.l&&this.D||this.unload()};
g.h.ZC=function(a,b,c,d,e){a&&(this.B.pD()&&(this.M=[],g.rV(this.I,"captions"),this.ba.sl()),a=Wza(this.B,a,b,c,d),this.A.experiments.g("debug_web_player_live_captions_segment_numbers")&&c&&e&&(c=a.reduce(function(a,b){return b.start<a?b.start:a},Number.MAX_SAFE_INTEGER),b=a.reduce(function(a,b){return b.end>a?b.end:a},c)-c,d=new c5(c,b,0,"_"+d5++,{If:2,
Pe:100,kg:0}),a.push(d),e=new b5(c,b,0,d.id,"sq="+e),a.push(e)),g.oV(this.g,a),this.K&&!this.ga&&cAa(this),this.K=!1)};
g.h.wM=function(a){this.M.push(a);this.ba.sl()};
g.h.xM=function(a){g.Sa(this.M,a);var b=Q5(this.o,this.I)&&this.A.Pa;!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.qV(this.g,[a]);this.ba.sl()};
g.h.KU=function(a){if(a instanceof c5){var b=this.R[a.id];b&&b.F!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=dAa(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.UU=function(){eAa(this,this.X);this.X=null};
g.h.QE=function(){this.ba.stop();g.Vb(this.Y);this.M.sort(g.rQ);var a=this.M;if(this.J){var b=(0,g.Id)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.KU,this);g.Hb(this.R,function(a,b){this.Y[b]?(a.element.parentNode||g.tV(this.g,a.element,4),a.Pi(this.Y[b])):(a.dispose(),delete this.R[b])},this)};
g.h.GD=function(){V5(this,{},!0)};
g.h.es=function(){var a=c6.fb;a={background:a.background,backgroundOpacity:a.df,charEdgeStyle:a.Wh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.qj,fontStyle:a.bold&&a.qf?3:a.bold?1:a.qf?2:0,textOpacity:a.Ih,windowColor:c6.windowColor,windowOpacity:c6.Mk};var b=W5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Kv=function(a,b){var c={};g.Fa(c,W5(this,"display-settings"));g.Fa(c,a);V5(this,c,b);this.g.T("captionssettingschanged")};
g.h.Hv=function(){!this.D&&this.loaded&&(g.Hb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.QE())};
g.h.Tt=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.$c(b,-2,4);this.Kv({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&b6(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.A.wb&&a6(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.D)break;if(!g.Ba(b))break;if(g.Ub(b)){b6(this,null,!0);break}var d;c=H5(this.B.l,!0);for(var e=0;e<c.length;e++){var f=c[e];f.l!=b.languageCode||d&&f.B!=b.languageName||(d=b.translationLanguage?
qza(f,b.translationLanguage):f)}!d||d==this.l&&this.loaded||b6(this,d,!0)}else return this.loaded&&this.l&&this.l!=Z5(this)?Z4(this.l):{};return"";case "tracklist":return this.B?(0,g.I)(H5(this.B.l,!(!b||!b.includeAsr)),function(a){return Z4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":d=this.es();if(g.OM(this.A)&&b&&g.Ba(b))if(b.reset)this.GD();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=gAa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=hAa(b[c],d[c]);break;case "charEdgeStyle":var k=g.T1[b[c]];f[c]=g.ua(k)?k:d[c];break;case "fontSizeIncrement":f[c]=iAa(b[c],d[c]);break;case "fontFamilyOption":k=g.S1[b[c]];f.fontFamily=
g.ua(k)?k:d[c];break;case "fontStyle":k=g.U1[b[c]],f[c]=g.ua(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.Kv(f,!0);d=this.es()}d.fontFamilyOption=g.ava[d.fontFamily];d.charEdgeStyle=g.bva[d.charEdgeStyle];d.fontStyle=g.cva[d.fontStyle];return d;case "sampleSubtitles":this.D||void 0==b||fAa(this,!!b);break;case "xmlTrack":b&&this.A.wb&&(this.D||b6(this,new g.FH({languageName:b.name}),!1,b.xml))}};
g.h.uM=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.wb&&a.push("stickyLoading","xmlTrack");return a};
g.h.vM=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.FE=function(){this.loaded&&this.l&&this.l!=Z5(this)?(a6(this,"module-enabled",!1),this.unload(),Y5(this,!0)&&b6(this,Z5(this),!1)):b6(this,this.l==Z5(this)?$5(this,!0):this.l,!0)};
g.h.iQ=function(){var a=this.l==Z5(this);Y5(this,a)?b6(this,this.g.getAudioTrack().Yn,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.PA()&&(a?b6(this,$5(this),!1):this.load()))};g.pY.captions=X5;})(_yt_player);
